# Generated by Django 6.0.2 on 2026-05-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Manufacturer or brand (e.g. Dell, Epson). Optional.', max_length=100),
        ),
    ]
