# Generated by Django 6.0.5 on 2026-06-04 14:58

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_conversationmember_cleared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.chat_upload_path),
        ),
    ]
