# Generated by Django 6.0.2 on 2026-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_drop_orphan_lockout_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='overdue_count',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime overdue incidents (never reset)'),
        ),
    ]
