# Generated by Django 6.0.5 on 2026-06-04 14:58

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.avatar_upload_path),
        ),
    ]
