# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text='Borrower credit score from 0 to 100',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='early_return_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Lifetime early confirmed returns',
            ),
        ),
    ]
