# Generated by Django 6.0.2 on 2026-05-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_update_normal_to_medium_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
