# Generated by Django 6.0.2 on 2026-06-03

from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_unread_overdue(apps, schema_editor):
    """Collapse pre-existing duplicate unread OVERDUE notifications so the
    partial unique constraint below can be created on an existing database.

    These duplicates were produced before the dedup/TOCTOU fix landed (e.g. by
    concurrent overdue scans during load testing). For each (recipient, request)
    we keep the most recent row (max id) and delete the older duplicates. Read
    notifications and request-less staff digests are untouched — they fall
    outside the constraint's condition. Reverse is a no-op (nothing to restore).
    """
    Notification = apps.get_model('requests', 'Notification')
    duplicate_groups = (
        Notification.objects
        .filter(is_read=False, type='OVERDUE', request__isnull=False)
        .values('recipient_id', 'request_id')
        .annotate(n=Count('id'), keep=Max('id'))
        .filter(n__gt=1)
    )
    for group in duplicate_groups:
        (
            Notification.objects
            .filter(
                is_read=False,
                type='OVERDUE',
                recipient_id=group['recipient_id'],
                request_id=group['request_id'],
            )
            .exclude(id=group['keep'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_request_return_confirmed_by_and_more'),
    ]

    operations = [
        # Clean up legacy duplicates BEFORE adding the constraint — otherwise
        # AddConstraint fails on databases that already hold duplicate rows.
        migrations.RunPython(dedupe_unread_overdue, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('is_read', False),
                    ('request__isnull', False),
                    ('type', 'OVERDUE'),
                ),
                fields=('recipient', 'request', 'type'),
                name='uniq_unread_overdue_notification',
            ),
        ),
    ]
