# Generated by Django 6.0.5 on 2026-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_unique_unread_overdue_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='auto_decided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='auto_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='auto_recommendation',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVIEW', 'Review')], default='', max_length=10),
        ),
    ]
