# Generated by Django 6.0.5 on 2026-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_request_auto_decided_request_auto_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='overdue_penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
